version: '2'

services:
  company:
    image: "danmerix/company:4"
    ports:
      - 80:80
    networks:
      - labas
  bank:
    image: "ricardaskazakevicius/superbank:v10"
    ports:
      - 90:1234
    depends_on:
      - company
    networks:
      - labas
networks:
  labas:
